/***** Project Header *****/
// Project Name:
// Version: 1
// Author:
// Date: 19/2/2020  11:49
// Code auto-generated by systemdesignerjs
//      from www.techideas.co.nz

/***** Hardware defines *****/
//make sure this matches your oscillator setting
#define F_CPU 16000000//crystal

/***** Includes *****/
#include <avr/io.h>
//#include <stdint.h>
#include <util/delay.h>
//#include <avr/interrupt.h>
//#include <avr/eeprom.h>
//#include <stdio.h>
//#include <string.h>
//#include <avr/pgmspace.h>
#include <avr/interrupt.h>

/***** Hardware macros *****/
//Hardware macros for outputs


#define SET_LED_1   PORTD |= (1<<PD6)
#define CLR_LED_1   PORTD &= ~(1<<PD6)

#define SET_LED_2   PORTD |= (1<<PD5)
#define CLR_LED_2   PORTD &= ~(1<<PD5)

#define SET_LED_3   PORTD |= (1<<PD4)
#define CLR_LED_3   PORTD &= ~(1<<PD4)

//Hardware macros for inputs
//Hardware macros for ADC inputs

/***** User macros *****/
#define DEL_TIME 1
/***** Declare & initialise global variables *****/

uint8_t i =0;
uint16_t count = 0;
/***** Interrupt Service Routines *****/
 ISR(TIMER1_COMPA_vect){
	 count++;
 }
 
/***** Prototypes  for Functions *****/
void num_zero();
void num_one();
void num_two();
void num_three();
void num_four();
void num_five();
void num_six();
void num_seven();
void num_eight();
void num_nine();


/***** Main function *****/
int main(void) {
    /***** Initial hardware setups go here *****/

    /***** IO Hardware Config *****/
    // configure these pins as outputs
	DDRD |= (1 << PD6);
	DDRD |= (1 << PD5);
	DDRD |= (1 << PD4);
	DDRB |= (1 << PB1); //setup OC1A pin (B1) as output

	/***** Timer Config *****/
	TCCR1B |= (1 << WGM12); // CTC mode
	TCCR1A |= (1 << COM1A0); // toggle OC1A (B1 )output on match
	TCCR1B |= (1 << CS12); // Prescaler /256
	OCR1A = 62499;
	TIMSK1 |= (1 << OCIE1A);
	 
	DDRC = 0xff;
	DDRB = 0xff;
	sei(); 
    // configure the internal pullup resistors for these pins

    /***** Main variables go here *****/

    /***** Run once code goes here *****/

    /***** Loop code *****/
    while (1) {
		
		
		
		switch (count)
		{
			case 1:
			PORTC = 0b0000100;
			PORTB = 0b1;
			CLR_LED_1;
			SET_LED_2;
			SET_LED_3;
			break;
			
			case 2:
			PORTC = 0b111010;
			PORTB = 0b1;
			CLR_LED_1;
			SET_LED_2;
			SET_LED_3;
			break;
			
			case 3:
			PORTC = 0b111100;
			PORTB = 0b1;
			CLR_LED_1;
			SET_LED_2;
			SET_LED_3;
			break;
			
			case 4:
			
			CLR_LED_1;
			SET_LED_2;
			SET_LED_3;
			break;
			
			case 5:
			num_five();
			CLR_LED_1;
			SET_LED_2;
			SET_LED_3;
			break;
			
			case 6:
			num_six();
			CLR_LED_1;
			SET_LED_2;
			SET_LED_3;
			break;
			
			case 7:
			num_seven();
			CLR_LED_1;
			SET_LED_2;
			SET_LED_3;
			break;
			
			case 8:
			num_eight();
			CLR_LED_1;
			SET_LED_2;
			SET_LED_3;
			break;
			
			case 9:
			num_nine();
			CLR_LED_1;
			SET_LED_2;
			SET_LED_3;
			break;
			
			default:
			PORTC = 0b0101111;
			PORTB = 0b1;
			CLR_LED_1;
			SET_LED_2;
			SET_LED_3;
		}
			
			/*CLR_LED_2;
			SET_LED_1;
			CLR_LED_3;
			
			PORTC = 0b111111;
			PORTB = 0b1;
			_delay_ms(DEL_TIME);
			SET_LED_2;
			CLR_LED_3;
			CLR_LED_1;
			PORTC = 0b01111010;
			PORTB = 0b00000001;
			_delay_ms(DEL_TIME);*/
    } //while end
} //main end
/***** Functions *****/

void num_four(){
	PORTC = 0b0010101;
	PORTB = 0b1;
}
void num_five(){
	PORTC = 0b111101;
	PORTB = 0b0;
}
void num_six(){
	PORTC = 0b111111;
	PORTB = 0b0;
}
void num_seven(){
	PORTC = 0b100100;
	PORTB = 0b1;
}
void num_eight(){
	PORTC = 0b111111;
	PORTB = 0b1;
}
void num_nine(){
	PORTC = 0b110101;
	PORTB = 0b1;
}